export const MANGALIB_STATUS_READING = 1;
export const MANGALIB_STATUS_PLANNED = 2;
export const MANGALIB_STATUS_DROPPED = 3;
export const MANGALIB_STATUS_READ = 4;
export const MANGALIB_STATUS_FAVOURITE = 5;

export const REMANGA_CATEGORY_READING = "Читаю";
export const REMANGA_CATEGORY_PLANNED = "Буду читать";
export const REMANGA_CATEGORY_DROPPED = "Брошено";
export const REMANGA_CATEGORY_READ = "Прочитано";
export const REMANGA_CATEGORY_FAVOURITE = "Любимое";

export const MANGALIB_STATUS_TO_REMANGA_NAME: Record<number, string> = {
  [MANGALIB_STATUS_READING]: REMANGA_CATEGORY_READING,
  [MANGALIB_STATUS_PLANNED]: REMANGA_CATEGORY_PLANNED,
  [MANGALIB_STATUS_DROPPED]: REMANGA_CATEGORY_DROPPED,
  [MANGALIB_STATUS_READ]: REMANGA_CATEGORY_READ,
  [MANGALIB_STATUS_FAVOURITE]: REMANGA_CATEGORY_FAVOURITE,
};

export function mapMangalibStatusToRemangaCategoryName(status: number): string {
  return MANGALIB_STATUS_TO_REMANGA_NAME[status] ?? REMANGA_CATEGORY_READING;
}
